// <auto-generated />
using AddressMicroService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressMicroService.Migrations
{
    [DbContext(typeof(AddressContext))]
    [Migration("20191125164735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddressMicroService.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            Country = "England",
                            FirstName = "John",
                            LastName = "Smith",
                            StreetAddress = "Test St 1"
                        },
                        new
                        {
                            Id = 2,
                            City = "london",
                            Country = "England",
                            FirstName = "Jane",
                            LastName = "Doe",
                            StreetAddress = "Test St 2"
                        },
                        new
                        {
                            Id = 3,
                            City = "New York",
                            Country = "USA",
                            FirstName = "Tim",
                            LastName = "Jones",
                            StreetAddress = "Test St 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
